# Generated by Django 4.0.4 on 2022-09-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1001)),
                ('file', models.FileField(upload_to='foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perDocumento', models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de extranjería', 'Cédula de extranjería')], max_length=200)),
                ('perNumeroDocumento', models.CharField(max_length=12)),
                ('perNombreCompleto', models.CharField(max_length=20)),
                ('perApellidos', models.CharField(max_length=30)),
                ('perSexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Intersexual', 'Intersexual'), ('Indefinido', 'Indefinido'), ('Prefieren no decir', 'Prefieren no decir')], max_length=20)),
                ('perTelefono', models.CharField(max_length=11)),
                ('perTelefonoFijo', models.CharField(max_length=11)),
                ('perCorreo', models.EmailField(max_length=20)),
                ('perMunicipio', models.CharField(max_length=10)),
                ('perDireccion', models.CharField(blank=True, max_length=30, null=True)),
                ('perBarrio', models.CharField(max_length=100)),
                ('perFechaNacimiento', models.DateField()),
                ('perEtnia', models.CharField(max_length=30)),
                ('perCondicionDiscapacidad', models.CharField(max_length=60)),
                ('perEstrato', models.CharField(max_length=3)),
                ('perUltimoNivelEducativo', models.CharField(max_length=25)),
                ('perDispositivo', models.BooleanField(default=False, max_length=100)),
                ('perTipoDispositivo', models.CharField(choices=[('T. Móvil', 'T. Móvil'), ('Computador', 'Computador'), ('Tablet', 'Tablet'), ('Otro', 'Otro')], max_length=100)),
                ('perConectividad', models.BooleanField(default=False, max_length=100)),
                ('perTipoAfiliacion', models.CharField(choices=[('Subsidiado', 'Subsidiado'), ('contributivo', 'contributivo')], max_length=100)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Sondeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonTipo', models.CharField(choices=[('Pregunta', 'Pregunta'), ('Fecha', 'Fecha'), ('Opciones de respuesta', 'Opciones de respuesta')], max_length=100)),
                ('sonTitulo', models.CharField(max_length=100)),
                ('sonFechaApertura', models.DateField()),
                ('sonHoraApertura', models.TimeField()),
                ('sonFechaCierre', models.DateField()),
                ('sonHoraCierre', models.TimeField()),
                ('sonRespuesta', models.CharField(max_length=100)),
                ('sonObservaciones', models.CharField(max_length=100)),
                ('sonPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.persona')),
            ],
            options={
                'db_table': 'sondeo',
            },
        ),
    ]
