# Generated by Django 4.0.6 on 2022-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_status_costumer_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='message',
            field=models.TextField(max_length=1001),
        ),
    ]
